x-env-variables: &env
  PB_ADMIN_EMAIL: ${PB_ADMIN_EMAIL}
  PB_ADMIN_PASSWORD: ${PB_ADMIN_PASSWORD}

services:
  pocketbase:
    build:
      context: .
    working_dir: /app
    ports:
      - 8090
    volumes:
      - "../pb_data:/app/pb_data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8090/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      <<: *env
